= Jmemory

A simple memory game for mobile, written in Google's cross-platform https://flutter.dev[Flutter] toolkit.

The 'j' at the front of the name is just to differentiate it from all the other memory games.
Or it could be j for Java, in which a few bits were initially prototyped.
Or it could the the j from https://darwinsys.com/andrej[Andrej, the son I lost to Type 1 Diabetes].

== Organization

* main.dart - the ubiquitous Flutter main program; includes build method for main screen
* globals.dart - a few global values
* tile.dart - one entry in the grid; based on its TileMode, shows blank button, a secret, or a checkmark.
* gameboard.dart - logic for filling the grid
* gamecontroller.dart - logic for determining matches and when you won.

== TODO

This repo at this point is just a proof-of-concept.
We need to replace the infrastructure with Flutter's own
Casual Games Toolkit
(cf https://docs.flutter.dev/resources/games-toolkit[the docs]).

=== Bugs

* Fix crash on device rotation, or disable rotation

=== Feature Requirements

* Fancy background, better use of screen real estate!
* Layout: text with rules and plays summary underneath main.
* Improve randomization algo
* More-competitive scoring
* Sound effect, animation or other notification on match.
* Generalize to 4x4/5x5/6x6/8x8
* Generalize to use images instead of numbers
* Settings dialog to control the above
